# TCL File Generated by Component Editor 18.1
# Thu Jun 02 15:05:14 BST 2022
# DO NOT MODIFY


# 
# RGB_HSV "RGB_HSV" v1.0
#  2022.06.02.15:05:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module RGB_HSV
# 
set_module_property DESCRIPTION ""
set_module_property NAME RGB_HSV
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Rover
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME RGB_HSV
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL RGB_TO_HSV
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file RGB_TO_HSV.sv SYSTEM_VERILOG PATH ip/RGB_TO_HSV/RGB_TO_HSV.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter IMAGE_W STD_LOGIC_VECTOR 640 ""
set_parameter_property IMAGE_W DEFAULT_VALUE 640
set_parameter_property IMAGE_W DISPLAY_NAME IMAGE_W
set_parameter_property IMAGE_W WIDTH 32
set_parameter_property IMAGE_W TYPE STD_LOGIC_VECTOR
set_parameter_property IMAGE_W ENABLED false
set_parameter_property IMAGE_W UNITS None
set_parameter_property IMAGE_W DESCRIPTION ""
set_parameter_property IMAGE_W HDL_PARAMETER true
add_parameter IMAGE_H STD_LOGIC_VECTOR 480
set_parameter_property IMAGE_H DEFAULT_VALUE 480
set_parameter_property IMAGE_H DISPLAY_NAME IMAGE_H
set_parameter_property IMAGE_H WIDTH 13
set_parameter_property IMAGE_H TYPE STD_LOGIC_VECTOR
set_parameter_property IMAGE_H ENABLED false
set_parameter_property IMAGE_H UNITS None
set_parameter_property IMAGE_H ALLOWED_RANGES 0:8191
set_parameter_property IMAGE_H HDL_PARAMETER true
add_parameter POINT INTEGER 12 ""
set_parameter_property POINT DEFAULT_VALUE 12
set_parameter_property POINT DISPLAY_NAME POINT
set_parameter_property POINT WIDTH ""
set_parameter_property POINT TYPE INTEGER
set_parameter_property POINT UNITS None
set_parameter_property POINT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property POINT DESCRIPTION ""
set_parameter_property POINT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 1
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source source_data data Output 24
add_interface_port avalon_streaming_source source_eop endofpacket Output 1
add_interface_port avalon_streaming_source source_ready ready Input 1
add_interface_port avalon_streaming_source source_sop startofpacket Output 1
add_interface_port avalon_streaming_source source_valid valid Output 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 1
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink sink_data data Input 24
add_interface_port avalon_streaming_sink sink_valid valid Input 1
add_interface_port avalon_streaming_sink sink_ready ready Output 1
add_interface_port avalon_streaming_sink sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink sink_eop endofpacket Input 1

