# TCL File Generated by Component Editor 18.1
# Thu Jun 16 17:12:59 BST 2022
# DO NOT MODIFY


# 
# CONTROL_DEMUX "CONTROL_DEMUX" v1.0
#  2022.06.16.17:12:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module CONTROL_DEMUX
# 
set_module_property DESCRIPTION ""
set_module_property NAME CONTROL_DEMUX
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Rover
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME CONTROL_DEMUX
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CONTROL_DEMUX
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file CONTROL_DEMUX.sv SYSTEM_VERILOG PATH CONTROL_DEMUX.sv TOP_LEVEL_FILE
add_fileset_file STREAM_REG_DEMUX.v VERILOG PATH STREAM_REG_DEMUX.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 1
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink sink_data data Input 24
add_interface_port avalon_streaming_sink sink_eop endofpacket Input 1
add_interface_port avalon_streaming_sink sink_ready ready Output 1
add_interface_port avalon_streaming_sink sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink sink_valid valid Input 1


# 
# connection point avalon_streaming_source_control
# 
add_interface avalon_streaming_source_control avalon_streaming start
set_interface_property avalon_streaming_source_control associatedClock clock
set_interface_property avalon_streaming_source_control associatedReset reset
set_interface_property avalon_streaming_source_control dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_control errorDescriptor ""
set_interface_property avalon_streaming_source_control firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_control maxChannel 0
set_interface_property avalon_streaming_source_control readyLatency 1
set_interface_property avalon_streaming_source_control ENABLED true
set_interface_property avalon_streaming_source_control EXPORT_OF ""
set_interface_property avalon_streaming_source_control PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_control CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_control SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_control source_data2 data Output 24
add_interface_port avalon_streaming_source_control source_eop2 endofpacket Output 1
add_interface_port avalon_streaming_source_control source_ready2 ready Input 1
add_interface_port avalon_streaming_source_control source_sop2 startofpacket Output 1
add_interface_port avalon_streaming_source_control source_valid2 valid Output 1


# 
# connection point avalon_streaming_source_data
# 
add_interface avalon_streaming_source_data avalon_streaming start
set_interface_property avalon_streaming_source_data associatedClock clock
set_interface_property avalon_streaming_source_data associatedReset reset
set_interface_property avalon_streaming_source_data dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_data errorDescriptor ""
set_interface_property avalon_streaming_source_data firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_data maxChannel 0
set_interface_property avalon_streaming_source_data readyLatency 1
set_interface_property avalon_streaming_source_data ENABLED true
set_interface_property avalon_streaming_source_data EXPORT_OF ""
set_interface_property avalon_streaming_source_data PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_data CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_data SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_data source_eop endofpacket Output 1
add_interface_port avalon_streaming_source_data source_ready ready Input 1
add_interface_port avalon_streaming_source_data source_sop startofpacket Output 1
add_interface_port avalon_streaming_source_data source_valid valid Output 1
add_interface_port avalon_streaming_source_data source_data data Output 24

